apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.label | toYaml }}
  name: klock-controller-manager-metrics-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{ .Values.label | toYaml }}
---
apiVersion: v1
kind: Service
metadata:
  name: klock-webhook-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{ .Values.label | toYaml }}